#!/usr/bin/env node
/*
 * Release script for SimpleWallet.
 *
 * Usage:
 *   node scripts/release.js [patch|minor|major|<x.y.z>] [options]
 *
 * Options:
 *   --build-only  Bump versionCode only, keeping the semantic version. Use when
 *                 Play rejects an upload and needs a fresh versionCode for the
 *                 same user-facing version.
 *   --dev         Build with the development configuration (default: production)
 *   --no-bump     Keep both the version and versionCode, only rebuild
 *   --no-clean    Skip removing www/ and .angular/cache
 *   --no-git      Do not commit nor tag the release
 *   --no-open     Do not open Android Studio at the end
 *   --dry-run     Print what would happen without touching anything
 *
 * package.json holds the single source of truth for the version. The script
 * propagates it to android/app/build.gradle (bumping versionCode by one) and
 * to src/environments/version.ts, which the app reads at runtime.
 */

const fs = require('fs');
const path = require('path');
const {execSync} = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const PKG = path.join(ROOT, 'package.json');
const LOCK = path.join(ROOT, 'package-lock.json');
const GRADLE = path.join(ROOT, 'android', 'app', 'build.gradle');
const VERSION_TS = path.join(ROOT, 'src', 'environments', 'version.ts');

const args = process.argv.slice(2);
const has = (flag) => args.includes(flag);
const bumpArg = args.find((a) => !a.startsWith('--')) || 'patch';

const opts = {
  buildOnly: has('--build-only'),
  dev: has('--dev'),
  bump: !has('--no-bump'),
  clean: !has('--no-clean'),
  git: !has('--no-git'),
  open: !has('--no-open'),
  dryRun: has('--dry-run'),
};

// --build-only touches versionCode only; --no-bump freezes both.
const bumpCode = opts.bump;
const bumpVersion = opts.bump && !opts.buildOnly;

const log = (msg) => console.log(`\x1b[36m▸\x1b[0m ${msg}`);
const warn = (msg) => console.log(`\x1b[33m!\x1b[0m ${msg}`);
const die = (msg) => {
  console.error(`\x1b[31m✗ ${msg}\x1b[0m`);
  process.exit(1);
};

function run(cmd, cwd = ROOT) {
  log(cmd);
  if (opts.dryRun) return;
  execSync(cmd, {cwd, stdio: 'inherit'});
}

function write(file, content) {
  if (opts.dryRun) return;
  fs.writeFileSync(file, content);
}

function nextVersion(current, kind) {
  if (/^\d+\.\d+\.\d+$/.test(kind)) return kind;
  const [major, minor, patch] = current.split('.').map(Number);
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  if (kind === 'patch') return `${major}.${minor}.${patch + 1}`;
  die(`Unknown bump "${kind}". Use patch | minor | major | x.y.z`);
}

// --- 1. Working tree must be clean --------------------------------------
if (opts.git && !opts.dryRun) {
  const dirty = execSync('git status --porcelain', {cwd: ROOT, encoding: 'utf8'}).trim();
  if (dirty) die(`Working tree is not clean. Commit or stash first:\n${dirty}`);
}

// --- 2. Resolve versions ------------------------------------------------
if (opts.buildOnly && !opts.bump) die('--build-only and --no-bump contradict each other.');
if (opts.buildOnly && args.includes(bumpArg) && args.some((a) => !a.startsWith('--'))) {
  warn(`--build-only ignores the "${bumpArg}" argument: the version stays put.`);
}

const pkg = JSON.parse(fs.readFileSync(PKG, 'utf8'));
const version = bumpVersion ? nextVersion(pkg.version, bumpArg) : pkg.version;

const gradleSrc = fs.readFileSync(GRADLE, 'utf8');
const currentCode = Number((gradleSrc.match(/versionCode\s+(\d+)/) || [])[1]);
if (!currentCode) die('Could not read versionCode from android/app/build.gradle');
const versionCode = bumpCode ? currentCode + 1 : currentCode;

console.log('');
log(`Version:     ${bumpVersion ? `${pkg.version} -> ${version}` : `${version} (unchanged)`}`);
log(`versionCode: ${bumpCode ? `${currentCode} -> ${versionCode}` : `${versionCode} (unchanged)`}`);
log(`Build:       ${opts.dev ? 'development' : 'production'}`);
if (opts.dryRun) warn('dry-run: no changes will be written');
console.log('');

// --- 3. Propagate the version ------------------------------------------
if (bumpVersion) {
  pkg.version = version;
  write(PKG, JSON.stringify(pkg, null, 2) + '\n');

  // package-lock.json keeps the version in two places (root + "" package).
  if (fs.existsSync(LOCK)) {
    const lock = JSON.parse(fs.readFileSync(LOCK, 'utf8'));
    lock.version = version;
    if (lock.packages && lock.packages['']) lock.packages[''].version = version;
    write(LOCK, JSON.stringify(lock, null, 2) + '\n');
  }
  log('Updated package.json and package-lock.json');
}

if (bumpCode) {
  write(
    GRADLE,
    gradleSrc
      .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
      .replace(/versionName\s+"[^"]*"/, `versionName "${version}"`)
  );
  log('Updated build.gradle');
}

// Always regenerate: keeps the app in sync even with --no-bump.
write(
  VERSION_TS,
  `// Generated by scripts/release.js -- do not edit by hand.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_BUILD = ${versionCode};\n`
);
log('Generated src/environments/version.ts');

// --- 4. Clean the web build --------------------------------------------
// The native side is intentionally left alone: Gradle is driven from Android
// Studio, which uses its own bundled JDK. Running ./gradlew from the CLI picks
// up the system JAVA_HOME instead, and Gradle 8.10 rejects Java 25 with
// "Unsupported class file major version 69". Use Build > Clean Project there.
if (opts.clean) {
  for (const dir of ['www', '.angular/cache']) {
    const target = path.join(ROOT, dir);
    if (fs.existsSync(target)) {
      log(`rm -rf ${dir}`);
      if (!opts.dryRun) fs.rmSync(target, {recursive: true, force: true});
    }
  }
}

// --- 5. Build + sync ----------------------------------------------------
run(`npx ng build --configuration ${opts.dev ? 'development' : 'production'}`);
// cap sync = copy + update: also refreshes native plugins, which cap copy does not.
run('npx cap sync android');

// --- 6. Commit + tag ----------------------------------------------------
function tagExists(tag) {
  try {
    execSync(`git rev-parse -q --verify refs/tags/${tag}`, {cwd: ROOT, stdio: 'pipe'});
    return true;
  } catch {
    return false;
  }
}

if (opts.git && bumpCode) {
  // v1.0.11 is already taken by the original release, so a re-upload of the same
  // version gets its own tag keyed by the build number.
  const tag = opts.buildOnly ? `v${version}-build${versionCode}` : `v${version}`;
  const message = opts.buildOnly
    ? `Bump build to ${versionCode} for v${version}`
    : `Release v${version} (build ${versionCode})`;

  run(`git add package.json package-lock.json android/app/build.gradle src/environments/version.ts`);
  run(`git commit -m "${message}"`);

  if (!opts.dryRun && tagExists(tag)) {
    warn(`Tag ${tag} already exists -- skipping tag. Committed anyway.`);
  } else {
    run(`git tag ${tag}`);
    console.log('');
    warn(`Tagged ${tag}. Push with: git push && git push --tags`);
  }
}

// --- 7. Open Android Studio --------------------------------------------
if (opts.open) run('npx cap open android');

console.log('');
console.log(`\x1b[32m✓ Web build for v${version} (build ${versionCode}) is ready\x1b[0m`);
console.log('  Now, in Android Studio:');
console.log('    1. Build > Clean Project');
console.log('    2. Build > Generate Signed App Bundle / APK');
