#!/usr/bin/env node
/*
 * Release script for SimpleWallet.
 *
 * Usage:
 *   node scripts/release.js [patch|minor|major|<x.y.z>] [options]
 *
 * Options:
 *   --dev         Build with the development configuration (default: production)
 *   --no-bump     Keep the current version, only rebuild
 *   --no-clean    Skip removing www/, .angular/cache and the gradle clean
 *   --no-git      Do not commit nor tag the release
 *   --no-open     Do not open Android Studio at the end
 *   --dry-run     Print what would happen without touching anything
 *
 * package.json holds the single source of truth for the version. The script
 * propagates it to android/app/build.gradle (bumping versionCode by one) and
 * to src/environments/version.ts, which the app reads at runtime.
 */

const fs = require('fs');
const path = require('path');
const {execSync} = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const PKG = path.join(ROOT, 'package.json');
const LOCK = path.join(ROOT, 'package-lock.json');
const GRADLE = path.join(ROOT, 'android', 'app', 'build.gradle');
const VERSION_TS = path.join(ROOT, 'src', 'environments', 'version.ts');

const args = process.argv.slice(2);
const has = (flag) => args.includes(flag);
const bumpArg = args.find((a) => !a.startsWith('--')) || 'patch';

const opts = {
  dev: has('--dev'),
  bump: !has('--no-bump'),
  clean: !has('--no-clean'),
  git: !has('--no-git'),
  open: !has('--no-open'),
  dryRun: has('--dry-run'),
};

const log = (msg) => console.log(`\x1b[36m▸\x1b[0m ${msg}`);
const warn = (msg) => console.log(`\x1b[33m!\x1b[0m ${msg}`);
const die = (msg) => {
  console.error(`\x1b[31m✗ ${msg}\x1b[0m`);
  process.exit(1);
};

function run(cmd, cwd = ROOT) {
  log(cmd);
  if (opts.dryRun) return;
  execSync(cmd, {cwd, stdio: 'inherit'});
}

function write(file, content) {
  if (opts.dryRun) return;
  fs.writeFileSync(file, content);
}

function nextVersion(current, kind) {
  if (/^\d+\.\d+\.\d+$/.test(kind)) return kind;
  const [major, minor, patch] = current.split('.').map(Number);
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  if (kind === 'patch') return `${major}.${minor}.${patch + 1}`;
  die(`Unknown bump "${kind}". Use patch | minor | major | x.y.z`);
}

// --- 1. Working tree must be clean --------------------------------------
if (opts.git && !opts.dryRun) {
  const dirty = execSync('git status --porcelain', {cwd: ROOT, encoding: 'utf8'}).trim();
  if (dirty) die(`Working tree is not clean. Commit or stash first:\n${dirty}`);
}

// --- 2. Resolve versions ------------------------------------------------
const pkg = JSON.parse(fs.readFileSync(PKG, 'utf8'));
const version = opts.bump ? nextVersion(pkg.version, bumpArg) : pkg.version;

const gradleSrc = fs.readFileSync(GRADLE, 'utf8');
const currentCode = Number((gradleSrc.match(/versionCode\s+(\d+)/) || [])[1]);
if (!currentCode) die('Could not read versionCode from android/app/build.gradle');
const versionCode = opts.bump ? currentCode + 1 : currentCode;

console.log('');
log(`Version:     ${pkg.version} -> ${version}`);
log(`versionCode: ${currentCode} -> ${versionCode}`);
log(`Build:       ${opts.dev ? 'development' : 'production'}`);
if (opts.dryRun) warn('dry-run: no changes will be written');
console.log('');

// --- 3. Propagate the version ------------------------------------------
if (opts.bump) {
  pkg.version = version;
  write(PKG, JSON.stringify(pkg, null, 2) + '\n');

  // package-lock.json keeps the version in two places (root + "" package).
  if (fs.existsSync(LOCK)) {
    const lock = JSON.parse(fs.readFileSync(LOCK, 'utf8'));
    lock.version = version;
    if (lock.packages && lock.packages['']) lock.packages[''].version = version;
    write(LOCK, JSON.stringify(lock, null, 2) + '\n');
  }

  write(
    GRADLE,
    gradleSrc
      .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
      .replace(/versionName\s+"[^"]*"/, `versionName "${version}"`)
  );
  log('Updated package.json, package-lock.json and build.gradle');
}

// Always regenerate: keeps the app in sync even with --no-bump.
write(
  VERSION_TS,
  `// Generated by scripts/release.js -- do not edit by hand.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_BUILD = ${versionCode};\n`
);
log('Generated src/environments/version.ts');

// --- 4. Clean -----------------------------------------------------------
if (opts.clean) {
  for (const dir of ['www', '.angular/cache']) {
    const target = path.join(ROOT, dir);
    if (fs.existsSync(target)) {
      log(`rm -rf ${dir}`);
      if (!opts.dryRun) fs.rmSync(target, {recursive: true, force: true});
    }
  }
  const gradlew = process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
  run(`${gradlew} clean`, path.join(ROOT, 'android'));
}

// --- 5. Build + sync ----------------------------------------------------
run(`npx ng build --configuration ${opts.dev ? 'development' : 'production'}`);
// cap sync = copy + update: also refreshes native plugins, which cap copy does not.
run('npx cap sync android');

// --- 6. Commit + tag ----------------------------------------------------
if (opts.git && opts.bump) {
  run(`git add package.json package-lock.json android/app/build.gradle src/environments/version.ts`);
  run(`git commit -m "Release v${version} (build ${versionCode})"`);
  run(`git tag v${version}`);
  console.log('');
  warn(`Tagged v${version}. Push with: git push && git push --tags`);
}

// --- 7. Open Android Studio --------------------------------------------
if (opts.open) run('npx cap open android');

console.log('');
console.log(`\x1b[32m✓ Release v${version} (build ${versionCode}) ready\x1b[0m`);
